"""pyGeoHet public API."""

from pygeohet._version import __version__
from pygeohet.core import (
    InteractionType,
    categorical_overlay,
    classify_interaction,
    q_statistic,
)
from pygeohet.detectors import (
    EcologicalDetector,
    FactorDetector,
    InteractionDetector,
    RiskDetector,
    ecological_detector,
    factor_detector,
    interaction_detector,
    risk_detector,
)
from pygeohet.models import (
    OPGD,
    GeoDetector,
    OPGDResult,
    SpatialScaleCandidateResult,
    SpatialScaleOPGD,
    SpatialScaleOPGDResult,
    SpatialScaleResult,
    compare_spatial_scales,
    geodetector,
    opgd,
)
from pygeohet.results import (
    EcologicalComparisonResult,
    EcologicalDetectorResult,
    FactorDetectorResult,
    GeoDetectorResult,
    InteractionComparisonResult,
    InteractionDetectorResult,
    QStatisticResult,
    RiskComparisonResult,
    RiskDetectorResult,
    RiskStratumSummary,
)
from pygeohet.stratification import (
    MSD,
    MSD_TIE_RULE,
    TIE_RULE,
    MSDResult,
    MSDScaleResult,
    OptimalStratificationResult,
    StratificationEvaluationResult,
    StratificationResult,
    canonical_method,
    evaluate_stratification,
    multiscale_discretize,
    optimize_stratification,
    stratify,
)

__all__ = [
    "__version__",
    "MSD",
    "MSDResult",
    "MSDScaleResult",
    "MSD_TIE_RULE",
    "TIE_RULE",
    "EcologicalComparisonResult",
    "EcologicalDetector",
    "EcologicalDetectorResult",
    "FactorDetector",
    "FactorDetectorResult",
    "GeoDetector",
    "GeoDetectorResult",
    "InteractionComparisonResult",
    "InteractionDetector",
    "InteractionDetectorResult",
    "InteractionType",
    "OPGD",
    "OPGDResult",
    "OptimalStratificationResult",
    "QStatisticResult",
    "RiskComparisonResult",
    "RiskDetector",
    "RiskDetectorResult",
    "RiskStratumSummary",
    "SpatialScaleCandidateResult",
    "SpatialScaleOPGD",
    "SpatialScaleOPGDResult",
    "SpatialScaleResult",
    "StratificationEvaluationResult",
    "StratificationResult",
    "canonical_method",
    "categorical_overlay",
    "classify_interaction",
    "compare_spatial_scales",
    "ecological_detector",
    "evaluate_stratification",
    "factor_detector",
    "geodetector",
    "interaction_detector",
    "multiscale_discretize",
    "opgd",
    "optimize_stratification",
    "q_statistic",
    "risk_detector",
    "stratify",
]
